replicaCount: 2

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-orders
  tag: "1.2.4"

service:
  type: ClusterIP
  port: 8084

resources:
  limits:
    cpu: 400m
    memory: 384Mi
  requests:
    cpu: 200m
    memory: 192Mi

serviceAccount:
  name: {{ .Values.serviceAccount.name }}
  roleArn: arn:aws:iam::<account-id>:role/<order-role-name>

namespace: {{ .Values.namespace | default "default" }}

postgresEndpoint: postgres-endpoint-from-terraform
