apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-ingress
  namespace: { { .Values.namespace | default "default" } }
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - cart.example.com
        - catalog.example.com
        - checkout.example.com
        - order.example.com
        - ui.example.com
      secretName: retail-tls-secret
  rules:
    - host: cart.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cart
                port:
                  number: 8081
    - host: catalog.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: catalog
                port:
                  number: 8082
    - host: checkout.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkout
                port:
                  number: 8083
    - host: order.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: order
                port:
                  number: 8084
    - host: ui.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 8080
