name: Build, Test, and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      KUBE_NAMESPACE: ${{ github.event_name == 'workflow_dispatch' && inputs.environment == 'prod' && secrets.KUBE_NAMESPACE_PROD || github.event_name == 'workflow_dispatch' && inputs.environment == 'staging' && secrets.KUBE_NAMESPACE_STAGING || secrets.KUBE_NAMESPACE_DEV }}
      KUBECONFIG: ${{ github.event_name == 'workflow_dispatch' && inputs.environment == 'prod' && secrets.KUBECONFIG_PROD || github.event_name == 'workflow_dispatch' && inputs.environment == 'staging' && secrets.KUBECONFIG_STAGING || secrets.KUBECONFIG_DEV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ github.event_name == 'workflow_dispatch' && inputs.environment == 'prod' && secrets.AWS_ROLE_ARN_PROD || github.event_name == 'workflow_dispatch' && inputs.environment == 'staging' && secrets.AWS_ROLE_ARN_STAGING || secrets.AWS_ROLE_ARN_DEV }}
          aws-region: us-east-1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install || true

      - name: Run tests
        run: |
          npm test || true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./environments/${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}

      - name: Extract Terraform Outputs
        id: tfoutputs
        run: |
          echo "MYSQL_ENDPOINT=$(terraform output -raw mysql_instance_endpoint)" >> $GITHUB_ENV
          echo "POSTGRES_ENDPOINT=$(terraform output -raw postgres_instance_endpoint)" >> $GITHUB_ENV
          echo "REDIS_ENDPOINT=$(terraform output -raw redis_cluster_endpoint)" >> $GITHUB_ENV
          echo "REDIS_PORT=$(terraform output -raw redis_cluster_port)" >> $GITHUB_ENV
          echo "DYNAMODB_TABLE_NAME=$(terraform output -raw dynamodb_table_name)" >> $GITHUB_ENV
        working-directory: ./environments/${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Helm values.yaml
        run: |
          yq e '.mysqlEndpoint = env(MYSQL_ENDPOINT)' -i helm/catalog/values.yaml
          yq e '.postgresEndpoint = env(POSTGRES_ENDPOINT)' -i helm/order/values.yaml
          yq e '.redisEndpoint = env(REDIS_ENDPOINT)' -i helm/checkout/values.yaml
          yq e '.redisPort = env(REDIS_PORT)' -i helm/checkout/values.yaml
          yq e '.dynamodbTableName = env(DYNAMODB_TABLE_NAME)' -i helm/cart/values.yaml
          yq e '.microservices.mysqlEndpoint = env(MYSQL_ENDPOINT)' -i helm/ui/values.yaml
          yq e '.microservices.postgresEndpoint = env(POSTGRES_ENDPOINT)' -i helm/ui/values.yaml
          yq e '.microservices.redisEndpoint = env(REDIS_ENDPOINT)' -i helm/ui/values.yaml
          yq e '.microservices.redisPort = env(REDIS_PORT)' -i helm/ui/values.yaml
          yq e '.microservices.dynamodbTableName = env(DYNAMODB_TABLE_NAME)' -i helm/ui/values.yaml
        shell: bash

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Install AWS Load Balancer Controller
        run: |
          helm repo add eks https://aws.github.io/eks-charts
          helm repo update
          LB_ROLE_ARN=$(terraform output -raw aws_load_balancer_controller_role_arn)
          helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
            --namespace kube-system \
            --set clusterName=$KUBE_NAMESPACE \
            --set serviceAccount.create=true \
            --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=$LB_ROLE_ARN
        working-directory: ./environments/${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}


      - name: Deploy with Helm
        run: |
          helm upgrade --install cart helm/cart --namespace $KUBE_NAMESPACE
          helm upgrade --install catalog helm/catalog --namespace $KUBE_NAMESPACE
          helm upgrade --install checkout helm/checkout --namespace $KUBE_NAMESPACE
          helm upgrade --install order helm/order --namespace $KUBE_NAMESPACE
          helm upgrade --install ui helm/ui --namespace $KUBE_NAMESPACE