name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      confirm_destroy:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: ${{ inputs.confirm_destroy == 'DESTROY' }}
    permissions:
      id-token: write
      contents: read
    env:
      KUBE_NAMESPACE: ${{ inputs.environment == 'prod' && secrets.KUBE_NAMESPACE_PROD || inputs.environment == 'staging' && secrets.KUBE_NAMESPACE_STAGING || secrets.KUBE_NAMESPACE_DEV }}
      KUBECONFIG: ${{ inputs.environment == 'prod' && secrets.KUBECONFIG_PROD || inputs.environment == 'staging' && secrets.KUBECONFIG_STAGING || secrets.KUBECONFIG_DEV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.environment == 'prod' && secrets.AWS_ROLE_ARN_PROD || inputs.environment == 'staging' && secrets.AWS_ROLE_ARN_STAGING || secrets.AWS_ROLE_ARN_DEV }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name $(terraform output -raw eks_cluster_name)
        working-directory: ./environments/${{ inputs.environment }}

      - name: Uninstall Helm releases
        run: |
          helm uninstall ui --namespace $KUBE_NAMESPACE || true
          helm uninstall order --namespace $KUBE_NAMESPACE || true
          helm uninstall checkout --namespace $KUBE_NAMESPACE || true
          helm uninstall catalog --namespace $KUBE_NAMESPACE || true
          helm uninstall cart --namespace $KUBE_NAMESPACE || true
          helm uninstall aws-load-balancer-controller --namespace kube-system || true
          helm uninstall external-secrets --namespace external-secrets-system || true

      - name: Delete Kubernetes resources
        run: |
          kubectl delete namespace $KUBE_NAMESPACE || true
          kubectl delete namespace external-secrets-system || true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Destroy
        run: |
          terraform init
          terraform destroy -auto-approve
        working-directory: ./environments/${{ inputs.environment }}